# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /data/data/com.termux/files/usr/bin/sh

# The CMake executable.
CMAKE_COMMAND = /data/data/com.termux/files/usr/bin/cmake

# The command to remove a file.
RM = /data/data/com.termux/files/usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/data/com.termux/files/home/MainInterface

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/data/com.termux/files/home/MainInterface

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/com.termux/files/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/com.termux/files/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/MainInterface/CMakeFiles /data/data/com.termux/files/home/MainInterface//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/MainInterface/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MI

# Build rule for target.
MI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MI
.PHONY : MI

# fast build rule for target.
MI/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/build
.PHONY : MI/fast

calc.o: calc.cpp.o
.PHONY : calc.o

# target to build an object file
calc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/calc.cpp.o
.PHONY : calc.cpp.o

calc.i: calc.cpp.i
.PHONY : calc.i

# target to preprocess a source file
calc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/calc.cpp.i
.PHONY : calc.cpp.i

calc.s: calc.cpp.s
.PHONY : calc.s

# target to generate assembly for a file
calc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/calc.cpp.s
.PHONY : calc.cpp.s

conv.o: conv.cpp.o
.PHONY : conv.o

# target to build an object file
conv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/conv.cpp.o
.PHONY : conv.cpp.o

conv.i: conv.cpp.i
.PHONY : conv.i

# target to preprocess a source file
conv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/conv.cpp.i
.PHONY : conv.cpp.i

conv.s: conv.cpp.s
.PHONY : conv.s

# target to generate assembly for a file
conv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/conv.cpp.s
.PHONY : conv.cpp.s

keygen.o: keygen.cpp.o
.PHONY : keygen.o

# target to build an object file
keygen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/keygen.cpp.o
.PHONY : keygen.cpp.o

keygen.i: keygen.cpp.i
.PHONY : keygen.i

# target to preprocess a source file
keygen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/keygen.cpp.i
.PHONY : keygen.cpp.i

keygen.s: keygen.cpp.s
.PHONY : keygen.s

# target to generate assembly for a file
keygen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/keygen.cpp.s
.PHONY : keygen.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/main.cpp.s
.PHONY : main.cpp.s

modules.o: modules.cpp.o
.PHONY : modules.o

# target to build an object file
modules.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/modules.cpp.o
.PHONY : modules.cpp.o

modules.i: modules.cpp.i
.PHONY : modules.i

# target to preprocess a source file
modules.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/modules.cpp.i
.PHONY : modules.cpp.i

modules.s: modules.cpp.s
.PHONY : modules.s

# target to generate assembly for a file
modules.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MI.dir/build.make CMakeFiles/MI.dir/modules.cpp.s
.PHONY : modules.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MI"
	@echo "... calc.o"
	@echo "... calc.i"
	@echo "... calc.s"
	@echo "... conv.o"
	@echo "... conv.i"
	@echo "... conv.s"
	@echo "... keygen.o"
	@echo "... keygen.i"
	@echo "... keygen.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... modules.o"
	@echo "... modules.i"
	@echo "... modules.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

